#!/bin/bash
# Common bash & zsh config file


######
# Moved from standard .bashrc
#
# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi


######
# Config
#
export MAKEFLAGS="-j5 -O2"
export WAFFLAGS="-j5 -O2"
#export FEATURES="distcc"

export TERM="xterm-color"

export EDITOR='vim'
export VISUAL='vim'

export PATH="${PATH}:${HOME}/bin"


######
# Aliases
#
alias ssh='ssh -CX'
alias vim='vim -p'
alias grep='grep --binary-files=without-match --color=auto'

alias th='wget -q http://dras.hu/wiki/tudasbazis/linux/tmux --header="X-DokuWiki-Do: export_xhtmlbody" -O - | elinks -force-html'
alias tn='nested-tmux-config'

alias rdesktop='rdesktop -zN'
alias rd='rdesktop -g 1670x980'

alias gl='git log --graph --decorate --color --oneline'

alias sl=ls
alias dc=cd

function add-gitignore() { curl "http://www.gitignore.io/api/$@" ;}


######
# Host specific settings
#
if [ -f "${HOME}/.myrc_host" ]; then
    . "${HOME}/.myrc_host"
fi
